name: flutter_clocks
description: A flutter widget that displays analog and digital clock widgets.
version: 1.0.0+1
homepage: https://github.com/gslender/flutter_clocks

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: